### ISSUE TITLE
Some gtk 3 issues

### ISSUE THREAD

**Issue by simonzack** [cedl38/zen-gtk-themes#1]
First of all, thanks for the great theme! It's my all time favorite gtk theme.

Upon upgrading to nemo 2.2.4 and gtk 3.14.3-2 on arch, I had some theming issues. Some of the buttons in the toolbar that previously blended into the background don't anymore:

![toolbar screenshot](https://cloud.githubusercontent.com/assets/628500/4743057/2e83873a-5a24-11e4-8ea3-06412789d570.png)

Ticks also don't exist in checkboxes anymore:

![checkboxes screenshot](https://cloud.githubusercontent.com/assets/628500/4743065/462c9d5e-5a24-11e4-9bfe-4aabcde711eb.png)

The scrollbar border when the mouse is over it is also a bit thick compared to gtk 2 applications.

Context menus also have a border not present on gtk 2 applications.

Wish I could send a PR but don't know a thing about gtk theming.

**Comment by cedryc** [comment]
Hello,

Thank you for your report. Theses bug are related to gtk3.14 and I've not upgraded this theme for it yet.

Unfortunately I've not so many time available at this time, so the fix can take some time.

Any patch is welcomed,
