### ISSUE TITLE
Support Gtk-3.18 

### ISSUE THREAD

**Issue by arkhan** [cedl38/zen-gtk-themes#5]
Its posible to add support to Gtk-3.18
Thanks

**Comment by cedryc** [comment]
Hello,

Sorry, I d'ont have time at this moment to update the theme.

If someone want to do it will be welcome

2016-02-21 23:58 GMT+01:00 Edison Ibañez notifications@github.com:

**Comment by computerix** [comment]
Hello,
Gtk-3.20 is completely broken...
Any chance to get it supported any time soon?
